# Generated by Django 4.2.5 on 2023-09-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_rename_bio_en_profile_bio_de"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="bio_de",
            new_name="bio_en",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="fb_image",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="temp_image",
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                max_length=200,
                null=True,
                upload_to="uploads/images/users/",
                verbose_name="Avatar",
            ),
        ),
    ]
