# Generated by Django 4.2.5 on 2023-10-13 16:11

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        (
            "users",
            "0001_squashed_0005_rename_bio_de_profile_bio_en_remove_profile_fb_image_and_more",  # noqa E501
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "image",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logo_image",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Logo",
                "verbose_name_plural": "Logos",
            },
        ),
    ]
