# Generated by Django 4.2.5 on 2023-10-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                ("link", models.URLField(verbose_name="Link")),
            ],
            options={
                "verbose_name": "Footer link",
                "verbose_name_plural": "Footer links",
            },
        ),
    ]
