# Generated by Django 4.2.5 on 2023-11-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_footerlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                max_length=200,
                null=True,
                upload_to="uploads/images/users/",
                verbose_name="Avatar",
            ),
        ),
    ]
