# Generated by Django 5.0 on 2024-02-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_footerlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                max_length=200,
                null=True,
                upload_to="uploads/images/users/",
                verbose_name="Avatar",
            ),
        ),
    ]
