# Generated by Django 5.0 on 2024-02-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_profile_avatar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="bio_en",
            new_name="bio_de",
        ),
    ]
