# Generated by Django 5.0 on 2024-02-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
