# Generated by Django 5.0.6 on 2024-05-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_rename_bio_en_profile_bio_de"),
        ("users", "0010_alter_profile_avatar"),
    ]

    operations = []
