# Generated by Django 5.0.3 on 2024-03-15 21:13

import django.db.models.deletion
import django.utils.timezone
import filer.fields.image
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shotgun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the article",
                        max_length=100,
                        verbose_name="Title",
                    ),
                ),
                ("body", tinymce.models.HTMLField(null=True, verbose_name="Text")),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Shotgun article",
                "verbose_name_plural": "Shotgun articles",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ShotgunImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Used in captions",
                        max_length=200,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        null=True, verbose_name="Position"
                    ),
                ),
                (
                    "filer_image",
                    filer.fields.image.FilerImageField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shotgun_filer_image",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
                (
                    "shot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shotgun_image",
                        to="pages.shotgun",
                        verbose_name="Article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shotgun image",
                "verbose_name_plural": "Shotgun images",
                "ordering": ["position"],
            },
        ),
    ]
